# Generated by Django 5.1.1 on 2024-10-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Waste_App', '0005_alter_message_recipient_alter_message_sender'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
